services:
  - type: web
    name: crypto-market-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 -b 0.0.0.0:$PORT app:socketio
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.9.0
