services:
  - type: web
    name: crypto-market-app
    env: python
    runtime: python3.11
    buildCommand: ./build.sh
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT wsgi:app
    healthCheckPath: /health
    static:
      - path: /static
        source: static
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: crypto-market-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: BINANCE_API_KEY
        sync: false
      - key: BINANCE_API_SECRET
        sync: false
      - key: COINMARKETCAP_API_KEY
        sync: false
      - key: MAIL_SERVER
        value: smtp.sendgrid.net
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USE_TLS
        value: true
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_DEFAULT_SENDER
        value: noreply@cryptomarket.example.com

  # Worker for background tasks (optional - if you need background processing)
  - type: worker
    name: crypto-market-worker
    env: python
    runtime: python3.11
    buildCommand: pip install -r requirements.txt
    startCommand: PYTHONPATH=. python worker.py
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: BINANCE_API_BASE_URL
        value: https://data-api.binance.vision
      - key: BINANCE_WS_BASE_URL
        value: wss://data-stream.binance.vision
      - key: COINMARKETCAP_API_KEY
        value: bda79d78-5f5c-41c3-892e-3584b698e234
      - key: COINMARKETCAP_API_URL
        value: https://pro-api.coinmarketcap.com/v1
      - key: DATABASE_URL
        fromDatabase:
          name: crypto-market-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: crypto-market-redis
          type: redis
          property: connectionString
      - key: MAIL_SERVER
        value: smtp.sendgrid.net
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USE_TLS
        value: true
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_DEFAULT_SENDER
        value: noreply@cryptomarket.example.com

  # Redis instance for caching and session management
  - type: redis
    name: crypto-market-redis
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    plan: free

# PostgreSQL database
databases:
  - name: crypto-market-db
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
